const fs = require('fs');
let c = fs.readFileSync('src/App.tsx', 'utf8');

const targetStart = "                                <div key={player.id} className={\`\${theme.bg} border-2 \${theme.border} rounded-[3.5rem] p-10 relative overflow-hidden transition-all \${theme.glow}\`}>";
const targetEnd = "                                   </div>\\n                                </div>";

let startIndex = c.indexOf(targetStart);
let endIndex = c.indexOf(targetEnd, startIndex);

if (startIndex === -1 || endIndex === -1) {
  console.log("Could not find start or end");
  process.exit(1);
}

const before = c.substring(0, startIndex);
const after = c.substring(endIndex + targetEnd.length);

const a1 = "                                <div key={player.id} className={' ' + theme.bg + ' border ' + theme.border + ' rounded-[28px] p-[22px] relative transition-all flex flex-col ' + theme.glow + ' mx-auto'} style={{ width: '330px', height: '430px' }}>\\n";
const a2 = "                                   {/* Rank Badge */}\\n";
const a3 = "                                   <div className={'absolute top-[22px] left-[22px] w-[58px] h-[58px] rounded-[16px] flex items-center justify-center font-black text-3xl shadow-sm z-10 bg-gradient-to-br ' + theme.rankColor + ' text-white'}>\\n";
const a4 = "                                      {!isTop3 && <div className=\\"absolute inset-0 bg-white/20 rounded-[16px]\\"></div>}\\n";
const a5 = "                                      <span className=\\"relative z-10\\">{i + 1}</span>\\n";
const a6 = "                                   </div>\\n\\n";
const a7 = "                                   {/* Background Watermark Avatar (silhouette) */}\\n";
const a8 = "                                   <div className=\\"absolute top-[35px] left-1/2 -translate-x-1/2 pointer-events-none opacity-[0.03]\\">\\n";
const a9 = "                                      <User size={180} />\\n";
const a10 = "                                   </div>\\n\\n";
const a11 = "                                   {/* Top 3 Icon */}\\n";
const a12 = "                                   {theme.icon && (\\n";
const a13 = "                                     <div className=\\"absolute top-10 right-10 z-10 bg-white/60 backdrop-blur-md p-2.5 rounded-[18px] border border-white shadow-inner\\">\\n";
const a14 = "                                       {theme.icon}\\n";
const a15 = "                                     </div>\\n";
const a16 = "                                   )}\\n\\n";
const a17 = "                                   <div className=\\"flex flex-col items-center justify-start flex-1 z-10 w-full mt-4\\">\\n";
const a18 = "                                      {/* Name Area */}\\n";
const a19 = "                                      <div className=\\"h-[92px] w-full flex items-center justify-center mb-6 mt-10\\">\\n";
const a20 = "                                         <h4 className=\\"text-[28px] font-black text-slate-800 text-center leading-snug line-clamp-2 px-2\\">\\n";
const a21 = "                                            {player.name}\\n";
const a22 = "                                         </h4>\\n";
const a23 = "                                      </div>\\n\\n";
const a24 = "                                      {/* Stats Box */}\\n";
const a25 = "                                      <div className=\\"w-[100%] h-[90px] bg-[#F8FAFC] rounded-[22px] border border-slate-100 flex items-stretch p-1 mb-4 shadow-sm z-10 mx-auto\\">\\n";
const a26 = "                                         {/* الأصوات */}\\n";
const a27 = "                                         <div className=\\"flex-1 flex flex-col items-center justify-center\\">\\n";
const a28 = "                                            <span className=\\"text-[10px] font-black text-slate-400 uppercase mb-1 flex items-center gap-1\\"><Users size={10} /> الأصوات</span>\\n";
const a29 = "                                            <span className=\\"text-xl font-black text-slate-700\\">{pts}</span>\\n";
const a30 = "                                         </div>\\n                                         \\n";
const a31 = "                                         {/* نقاط المسابقة */}\\n";
const a32 = "                                         <div className=\\"flex-1 flex flex-col items-center justify-center border-r border-slate-200/60\\">\\n";
const a33 = "                                            <span className=\\"text-[10px] font-black text-slate-400 uppercase mb-1 text-center leading-tight flex items-center gap-1\\"><Star size={10} /> نقاط المسابقة</span>\\n";
const a34 = "                                            <span className=\\"text-xl font-black text-slate-700\\">{compPts}</span>\\n";
const a35 = "                                         </div>\\n\\n";
const a36 = "                                         {/* الرصيد العادي */}\\n";
const a37 = "                                         {includeNormalCredit && (\\n";
const a38 = "                                            <div className=\\"flex-1 flex flex-col items-center justify-center border-r border-slate-200/60\\">\\n";
const a39 = "                                               <span className=\\"text-[10px] font-black text-slate-400 uppercase mb-1 text-center leading-tight flex items-center gap-1\\"><Wallet size={10} /> الرصيد العادي</span>\\n";
const a40 = "                                               <span className=\\"text-xl font-black text-slate-700\\">{normalCredit}</span>\\n";
const a41 = "                                            </div>\\n";
const a42 = "                                         )}\\n\\n";
const a43 = "                                         {/* المجموع */}\\n";
const a44 = "                                         <div className={'w-[75px] mr-1 rounded-[18px] flex flex-col items-center justify-center text-white shadow-sm ' + (isTop3 ? 'bg-gradient-to-b ' + theme.rankColor : 'bg-gradient-to-b from-indigo-500 to-indigo-600')}>\\n";
const a45 = "                                            <span className=\\"text-[10px] font-black opacity-90 uppercase mt-0.5 mb-1 flex items-center gap-1 text-center leading-tight\\"><Trophy size={10} /> المجموع</span>\\n";
const a46 = "                                            <span className=\\"text-[24px] font-black leading-none\\">{totalPoints}</span>\\n";
const a47 = "                                         </div>\\n";
const a48 = "                                      </div>\\n\\n";
const a49 = "                                      {/* Badges Area */}\\n";
const a50 = "                                      <div className=\\"w-full h-[90px] flex flex-wrap items-start justify-center gap-2 content-start overflow-hidden z-10 px-0 mt-2\\">\\n";
const a51 = "                                         {hasDebt && (\\n";
const a52 = "                                            <div className=\\"px-[12px] h-[36px] rounded-[18px] text-[11px] font-black flex items-center gap-1 border bg-rose-50 border-rose-100 text-rose-600 truncate max-w-full\\">\\n";
const a53 = "                                               <Info size={12} className=\\"shrink-0\\" />\\n";
const a54 = "                                               <span className=\\"truncate\\">لم يسدد اشتراك</span>\\n";
const a55 = "                                            </div>\\n";
const a56 = "                                         )}\\n";
const a57 = "                                         {didNotVote && (\\n";
const a58 = "                                            <div className=\\"px-[12px] h-[36px] rounded-[18px] text-[11px] font-black flex items-center gap-1 border bg-orange-50 border-orange-100 text-orange-600 truncate max-w-full\\">\\n";
const a59 = "                                               <MicOff size={12} className=\\"shrink-0\\" />\\n";
const a60 = "                                               <span className=\\"truncate\\">لم يصوّت للآخرين</span>\\n";
const a61 = "                                            </div>\\n";
const a62 = "                                         )}\\n";
const a63 = "                                         {showTieBreakReasons && attendanceCount > 0 && (\\n";
const a64 = "                                            <div className=\\"px-[12px] h-[36px] rounded-[18px] text-[11px] font-black flex items-center gap-1 border bg-emerald-50 border-emerald-100 text-emerald-600 truncate max-w-full\\">\\n";
const a65 = "                                               <CheckCircle size={12} className=\\"shrink-0\\" />\\n";
const a66 = "                                               <span className=\\"truncate\\">حضور {attendanceCount} مرة</span>\\n";
const a67 = "                                            </div>\\n";
const a68 = "                                         )}\\n";
const a69 = "                                         {showTieBreakReasons && lateCount > 0 && (\\n";
const a70 = "                                            <div className=\\"px-[12px] h-[36px] rounded-[18px] text-[11px] font-black flex items-center gap-1 border bg-slate-100 border-slate-200 text-slate-600 truncate max-w-full\\">\\n";
const a71 = "                                               <Clock size={12} className=\\"shrink-0\\" />\\n";
const a72 = "                                               <span className=\\"truncate\\">تأخر {lateCount} مرات</span>\\n";
const a73 = "                                            </div>\\n";
const a74 = "                                         )}\\n";
const a75 = "                                         {showTieBreakReasons && earlyCount > 0 && (\\n";
const a76 = "                                            <div className=\\"px-[12px] h-[36px] rounded-[18px] text-[11px] font-black flex items-center gap-1 border bg-sky-50 border-sky-100 text-sky-600 truncate max-w-full\\">\\n";
const a77 = "                                               <FastForward size={12} className=\\"shrink-0\\" />\\n";
const a78 = "                                               <span className=\\"truncate\\">مبكر {earlyCount} مرة</span>\\n";
const a79 = "                                            </div>\\n";
const a80 = "                                         )}\\n";
const a81 = "                                      </div>\\n";
const a82 = "                                   </div>\\n";
const a83 = "                                </div>";

const res = a1+a2+a3+a4+a5+a6+a7+a8+a9+a10+a11+a12+a13+a14+a15+a16+a17+a18+a19+a20+a21+a22+a23+a24+a25+a26+a27+a28+a29+a30+a31+a32+a33+a34+a35+a36+a37+a38+a39+a40+a41+a42+a43+a44+a45+a46+a47+a48+a49+a50+a51+a52+a53+a54+a55+a56+a57+a58+a59+a60+a61+a62+a63+a64+a65+a66+a67+a68+a69+a70+a71+a72+a73+a74+a75+a76+a77+a78+a79+a80+a81+a82+a83;

fs.writeFileSync('src/App.tsx', before + res + after);
console.log("Success");
